name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-BE:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: install deps
        working-directory: backend
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: backend
        env:
          DATABASE_URL: file:../test.db
          JWT_SECRET: "secret"
          PORT: "8080"
        run: make test-cov

  test-FE:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: install deps
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: frontend
        run: make test-cov
