name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-be:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install deps
        working-directory: backend
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: backend
        env:
          DATABASE_URL: file:../test.db
          JWT_SECRET: 'secret'
          PORT: '8080'
        run: make test-cov

  test-fe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install deps
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: frontend
        run: make test-cov

  test-e2e-playwright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps chromium --only-shell

      - name: Run tests
        run: make test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
